config/routes.rb
Tfa::Application.routes.draw do
	devise_for :users, :controllers => { :registrations => "registrations" }
	authenticated :user do
		root :to => 'home#index'
		resources :users do
			member do
				get "reset_secret" => "users#reset_secret"
				get "delete_qr_code" => "users#delete_qr_code"
			end
		end
	end
	devise_scope :user do
		root :to => "devise/sessions#new"
	end
	resources :users
end

app/models/ability.rb
class Ability
	include CanCan::Ability

	def initialize(user)
		user ||= User.new # guest user (not logged in)
		if user.has_role? :admin
			can :manage, :all
		elsif user.has_role? :user
			#can :read, :all
			can [:read, :update, :reset_secret], User do |account|
				account.email == user.email
			end
		end
	end
end
# Define abilities for the passed in user here. For example:
#
#   user ||= User.new # guest user (not logged in)
#   if user.admin?
#     can :manage, :all
#   else
#     can :read, :all
#   end
#
# The first argument to `can` is the action you are giving the user permission to do.
# If you pass :manage it will apply to every action. Other common actions here are
# :read, :create, :update and :destroy.
#
# The second argument is the resource the user can perform the action on. If you pass
# :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
#
# The third argument is an optional hash of conditions to further filter the objects.
# For example, here the user can only update published articles.
#
#   can :update, Article, :published => true
#
# See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users, :join_table => :users_roles
	belongs_to :resource, :polymorphic => true

	scopify
end

app/models/user.rb
class User < ActiveRecord::Base
	rolify
	# Include default devise modules. Others available are:
	# :token_authenticatable, :confirmable,
	# :lockable, :timeoutable and :omniauthable
	devise :two_factor_authenticatable, :database_authenticatable, :registerable,
		:recoverable, :trackable, :validatable

	# Setup accessible (or protected) attributes for your model
	attr_accessible :role_ids, :as => :admin
	attr_accessible :name, :email, :password, :password_confirmation, :otp_secret
	validates :email, :uniqueness => true

	after_create :assign_default_role

	def assign_default_role
		add_role(:user) if self.roles.blank?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery

	rescue_from CanCan::AccessDenied do |exception|
		redirect_to root_path, :alert => exception.message
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@users = User.all
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	protected

	def after_sign_up_path_for(resource)
		user = User.find(current_user.id)
		user.otp_secret = ROTP::Base32.random_base32
		user.save
		reset_secret_user_path(current_user.id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource
	before_filter :authenticate_user!

	def index
		authorize! :index, @user, :message => 'Not authorized as an administrator.'
		@users = User.all
	end

	def update
		authorize! :update, @user, :message => 'Not authorized as an administrator.'
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user], :as => :admin)
			redirect_to users_path, :notice => "User updated."
		else
			redirect_to users_path, :alert => "Unable to update user."
		end
	end

	def destroy
		authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
		user = User.find(params[:id])
		unless user == current_user
			user.destroy
			redirect_to users_path, :notice => "User deleted."
		else
			redirect_to users_path, :notice => "Can't delete yourself."
		end
	end

	def show
		@user = User.find(params[:id])
		@totp = ROTP::TOTP.new(@user.otp_secret)
		@qr_string = @totp.provisioning_uri("auth test - #{@user.email}")
		@qr_code = QREncoder.encode(@qr_string)
		@qr_code.png(pixels_per_module: 4, margin: 1).save("public/images/qrcode-#{@user.id}.png")
	end

	def delete_qr_code
		@user = User.find(params[:id])
		if File.exists?("public/images/qrcode-#{@user.id}.png")
			File.delete("public/images/qrcode-#{@user.id}.png")
		end
		redirect_to root_path
	end

	def reset_secret
		@user = User.find(params[:id])
		@user.otp_secret = ROTP::Base32.random_base32
		@user.save
		redirect_to user_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
<% if current_user.has_role? :admin %>
	<p>Welcome, admin</p>
<% else %>
	<p>Welcome, user</p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= nav_bar :brand => "Authorization Application", :responsive => true, :brand_link => root_path do %>
	<% menu_group :pull => :right do %>
		<% if user_signed_in? %>
			<%= menu_item "Edit account", edit_user_registration_path %>
			<% if current_user.has_role? :admin %>
				<%= drop_down "Admin" do %>
					<%= menu_item "Manage users", users_path %>
				<% end %>
			<% end %>
		<% end %>
		<% if user_signed_in? %>
			<%= menu_item "Log out", destroy_user_session_path, :method => :delete %>
		<% end %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Tfa" %></title>
<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tfa" %>">
<%= stylesheet_link_tag :bootstrap %>
<%= stylesheet_link_tag :bootstrap_and_overrides %>
<%= javascript_include_tag :bootstrap %>
<%= javascript_include_tag :application %>
<%= javascript_include_tag :home %>
<%= csrf_meta_tags %>
<%= yield(:head) %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
<div id="container" class="container">
	<div class="row-fluid">
		<div class="span12">
			<%= render 'layouts/navigation' %>
			<%= bootstrap_flash %>
		</div>
	</div>
	<div id="main" role="main">
		<%= yield %>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<footer>
			</footer>
		</div>
	</div>
</div> <!--! end of #container -->
</body>
</html>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Roles</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
	  <td><%= user.roles.collect{|r| r.name }.join(", ") %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<div class="row">
	<h1>OTP Secret Reset</h1>
	<% if current_user.id == @user.id %>
		<h3>Use Google Authenticator to scan this QR code:</h3>
		<div id="qrcode">
			<img alt="qr code" src=<%= "/images/qrcode-#{@user.id}.png" %> />
		</div>
		<h3>Or enter this code manually:</h3>
		<pre><%= @user.otp_secret %></pre>
		<br/>
	<% else %>
		<h3>You are not authorized to view this user's OTP secret</h3>
	<% end %>
	<%= button_to "OK", delete_qr_code_user_path, :class => 'btn-primary', :method => :get %>
</div>